### ISSUE TITLE
Unable to download Bethini Pie

### ISSUE THREAD

**Issue by Chimpidge** [cacophony-wj/licentia_black#25]
Hello,

I ran into an issue at the end of the download. I'm not sure where it went wrong. I've followed all of the instructions in the installation section of the readme including uninstalling my anti virus and adding exceptions through Windows Defender for my solid state X:\Licentia Black, the Skyrim vanilla game folder, and the Wabbajack executable folder. Is this an antivirus issue? Or something else preventing the modding tools from downloading?

00:00:18.616 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Bethini Pie-631-4-11-1714357636.zip
00:00:19.164 [INFO] (Wabbajack.Networking.NexusApi.ProxiedNexusApi) Nexus API call finished: 0.025202 - Remaining Limit: 0
00:00:19.431 [INFO] (Wabbajack.Networking.NexusApi.ProxiedNexusApi) Nexus API call finished: 0.038416 - Remaining Limit: 8571
00:00:19.431 [INFO] (Wabbajack.Downloaders.NexusDownloader) Downloading Nexus File: ModdingTools|631|2401
00:00:19.442 [DEBUG] (Wabbajack.Networking.Http.SingleThreadedDownloader) Download for 'Bethini Pie-631-4-11-1714357636.zip' is starting from scratch...
00:00:22.056 [INFO] (Wabbajack.Downloaders.DownloadDispatcher) Finished downloading Bethini Pie-631-4-11-1714357636.zip. Hash: 1Zbv48+smj8=; Size: 21.7MB/19.1MB
00:00:41.948 [FATAL] (Wabbajack.Downloaders.DownloadDispatcher) While finding mirror for 1vu+CR0B1TY=|System.NullReferenceException: Object reference not set to an instance of an object.
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 83
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 124
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 116
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 57
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadFromMirror(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 252
00:00:41.966 [ERROR] (Wabbajack.Installer.StandardInstaller) Downloaded hash AAAAAAAAAAA= does not match expected hash: 1vu+CR0B1TY=
00:00:41.966 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:00:41.966 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:00:41.992 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:00:42.294 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:00:42.294 [INFO] (Wabbajack.Installer.StandardInstaller) Found 17764 total files, 2777 matching filesize
00:00:42.899 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Bethini Pie-631-4-11-1714357636.zip (NexusDownloader+State|ModdingTools|631|2401)
00:00:42.899 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

**Comment by Chimpidge** [comment]
Manual download of the Bethini Pie into the mod folder resolved the issue.
