### ISSUE TITLE
i have problems

### ISSUE THREAD

**Issue by willy3215** [cacophony-wj/licentia_black#5]
############ Wabbajack log file - 2022-12-21 18:46:52.8583 ############
00:00:00.000 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 228980, Name = Steamworks Common Redistributables, Path = C:\Program Files (x86)\Steam\steamapps\common\Steamworks Shared }
00:00:00.009 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 251570, Name = 7 Days to Die, Path = D:\SteamLibrary\steamapps\common\7 Days To Die }
00:00:00.009 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 384300, Name = CPUCores :: Maximize Your FPS, Path = D:\SteamLibrary\steamapps\common\CPUCores }
00:00:00.009 [DEBUG] (Wabbajack.Downloaders.GameFile.GameLocator) Found SteamGame { AppId = 489830, Name = The Elder Scrolls V: Skyrim Special Edition, Path = D:\SteamLibrary\steamapps\common\Skyrim Special Edition }
00:00:00.023 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Game does not exist: GOGGame { Id = 1603921704, Name = Winkeltje: The Little Shop, Path = D:\Crack Games\Winkeltje The Little Shop }
00:00:00.023 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Game does not exist: EGSGame { CatalogItemId = 098f795d4a9f4b108ca211f6b3e90a01, DisplayName = Hello Mod Kit, InstallLocation = D:\Crack Games\Voidtrain\ }
00:00:00.023 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) Manifest folder C:\ProgramData\Origin\LocalContent does not contain any .mfst files
00:00:00.695 [INFO] (Wabbajack.MainWindowVM) Assembly Location: 
00:00:00.695 [INFO] (Wabbajack.MainWindowVM) Process Location: D:\Wabbajack\3.0.4.1\Wabbajack.exe
00:00:00.695 [INFO] (Wabbajack.MainWindowVM) Wabbajack Version: 3.0.4.1
00:00:00.933 [INFO] (Wabbajack.MainWindow) Wabbajack Build - 8c60dc1197af3158fd844a3f0ae068766df2f0fc
00:00:00.933 [INFO] (Wabbajack.MainWindow) Running in D:\Wabbajack\3.0.4.1
00:00:00.987 [INFO] (Wabbajack.MainWindow) Detected Windows Version: Microsoft Windows NT 10.0.19045.0
00:00:00.987 [INFO] (Wabbajack.MainWindow) System settings - (64GB RAM) (18.5GB Page), Display: 1920 x 1080 (7.9GB VRAM - VideoMemorySizeMb=10240)
00:00:00.988 [INFO] (Wabbajack.MainWindow) Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance
00:00:01.010 [INFO] (Wabbajack.LauncherUpdater) Getting new Wabbajack version list
00:00:33.747 [INFO] (Wabbajack.InstallerVM) Preparing HttpDownloader
00:00:33.747 [INFO] (Wabbajack.InstallerVM) Preparing NexusDownloader
00:00:33.747 [INFO] (Wabbajack.InstallerVM) Preparing GameFileDownloader
00:00:33.747 [INFO] (Wabbajack.InstallerVM) Preparing ManualDownloader
00:00:33.747 [INFO] (Wabbajack.InstallerVM) Preparing MegaDownloader
00:00:35.450 [INFO] (Wabbajack.InstallerVM) Preparing WabbajackCDNDownloader
00:00:35.450 [INFO] (Wabbajack.InstallerVM) Preparing GoogleDriveDownloader
00:00:35.482 [INFO] (Wabbajack.Installer.StandardInstaller) Installing: Licentia BLACK - 0.0.1.0
00:00:35.824 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Configuring Installer
00:00:35.824 [INFO] (Wabbajack.Installer.StandardInstaller) Configuring Processor
00:00:35.824 [INFO] (Wabbajack.Installer.StandardInstaller) Install Folder: D:\Licentia BLACK
00:00:35.824 [INFO] (Wabbajack.Installer.StandardInstaller) Downloads Folder: D:\Licentia BLACK\downloads
00:00:35.824 [INFO] (Wabbajack.Installer.StandardInstaller) Game Folder: D:\SteamLibrary\steamapps\common\Skyrim Special Edition
00:00:35.824 [INFO] (Wabbajack.Installer.StandardInstaller) Wabbajack Folder: D:\Wabbajack\3.0.4.1
00:00:35.824 [INFO] (Wabbajack.Installer.StandardInstaller) Optimizing ModList directives
00:00:36.993 [WARN] (Wabbajack.InstallerVM) While loading slide|System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Wabbajack.InstallerVM.PopulateNextModSlide(ModList modList)
00:00:40.502 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for files to delete
00:00:40.527 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Cleaning empty folders
00:00:41.836 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for unmodified files
00:00:42.013 [WARN] (Wabbajack.InstallerVM) While loading slide|System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Wabbajack.InstallerVM.PopulateNextModSlide(ModList modList)
00:00:42.830 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Updating ModList
00:00:42.830 [INFO] (Wabbajack.Installer.StandardInstaller) Optimized 384752 directives to 384752 required
00:00:42.914 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:00:42.914 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:00:42.914 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:00:42.952 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:00:42.957 [INFO] (Wabbajack.Installer.StandardInstaller) Found 1484 total files, 1379 matching filesize
00:00:43.167 [INFO] (Wabbajack.Installer.StandardInstaller) Missing 4 archives
00:00:43.167 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading validation data
00:00:43.648 [INFO] (Wabbajack.Installer.StandardInstaller) Validating Archives
00:00:43.648 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading missing archives
00:00:43.648 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading 4 archives
00:00:43.648 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Downloading files
00:00:43.648 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Data_ccbgssse034-mntuni.esl
00:00:43.662 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Data_ccbgssse034-mntuni.esl|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
   at Wabbajack.Downloaders.Interfaces.ADownloader`1.Download(Archive archive, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Interfaces\ADownloader.cs:line 26
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 136
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in C:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 393
00:00:43.662 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Data_ccmtysse002-ve.esl
00:00:43.662 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Data_ccmtysse002-ve.esl|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
   at Wabbajack.Downloaders.Interfaces.ADownloader`1.Download(Archive archive, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Interfaces\ADownloader.cs:line 26
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 136
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in C:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 393
00:00:43.662 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Data_ccbgssse034-mntuni.bsa
00:00:43.662 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Data_ccbgssse034-mntuni.bsa|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
   at Wabbajack.Downloaders.Interfaces.ADownloader`1.Download(Archive archive, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Interfaces\ADownloader.cs:line 26
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 136
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in C:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 393
00:00:43.662 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Data_ccmtysse002-ve.bsa
00:00:43.662 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Data_ccmtysse002-ve.bsa|System.NotImplementedException: The method or operation is not implemented.
   at Wabbajack.Downloaders.GameFile.GameFileDownloader.Download(Archive archive, GameFileSource state, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.GameFile\GameFileDownloader.cs:line 29
   at Wabbajack.Downloaders.Interfaces.ADownloader`1.Download(Archive archive, AbsolutePath destination, IJob job, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Interfaces\ADownloader.cs:line 26
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in C:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 136
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in C:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 393
00:00:43.662 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:00:43.662 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:00:43.677 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:00:43.677 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:00:43.677 [INFO] (Wabbajack.Installer.StandardInstaller) Found 1484 total files, 1379 matching filesize
00:00:43.838 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccbgssse034-mntuni.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.640.0|data\ccbgssse034-mntuni.bsa)
00:00:43.838 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccmtysse002-ve.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.640.0|data\ccmtysse002-ve.bsa)
00:00:43.838 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccbgssse034-mntuni.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.640.0|data\ccbgssse034-mntuni.esl)
00:00:43.838 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccmtysse002-ve.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.640.0|data\ccmtysse002-ve.esl)
00:00:43.838 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

**Comment by Cr41gy** [comment]
I guess, you don't have the Creation Club content of the anniversary edition installed. I had similar problems, but it worked after the cc content was finally downloaded.
